min_dm: 50.0
min_dm_dsc: "smallest dm in filtering"
min_snr: 8.0
min_snr_dsc: "smallest snr in filtering"
writeT1: True
writeT1_dsc: "write the clustered, unfiltered T1 candidates"
min_snr_t2out: 7.5
min_snr_t2out_dsc: "min SNR in T2 out"
use_gal_dm: True
use_gal_dm_dsc: "use the ne2001 MW model to set DM limit"

