min_dm: 55.0
min_dm_dsc: "smallest dm in filtering"
max_ibox: 33
max_ibox_dsc: "largest ibox in filtering"
min_snr: 9.5
min_snr_dsc: "smallest snr in filtering"
max_ncl: 100000
max_ncl_dsc: "largest number of clusters allowed in triggering"
max_ctb: 21
max_ctb_dsc: "maximum number of beams in cluster"
min_snr_t2out: 7.5
min_snr_t2out_dsc: "min SNR in T2 out"
