max_ibox: 33
max_ibox_dsc: largest ibox in filtering
max_ncl: 100000
max_ncl_dsc: largest number of clusters allowed in triggering
min_dm: 25.0
min_dm_dsc: smallest dm in filtering
min_snr: 9.0
min_snr_dsc: smallest snr in filtering
min_snr_t2out: 7.5
min_snr_t2out_dsc: smallest snr in T2 file output
max_ctb: 21,
max_ctb_dsc: maximum number of beams in cluster