min_dm: 50.0
min_dm_dsc: "smallest dm in filtering"
min_snr: 8.4
min_snr_dsc: "smallest snr in filtering"
min_snr_wide: 9.8
min_snr_wide_dsc: "smallest snr in filtering of wide events"
max_ibox: 33
max_ibox_dsc: "largest ibox in filtering"
wide_ibox: 17
wide_ibox_dsc: "min_snr_wide used for ibox>=wide_ibox"
max_ncl: 30
max_ncl_dsc: "largest number of clusters allowed in triggering"
max_ctb0: 7
max_ctb0_dsc: "maximum number of beams in cluster at min_snr"
max_ctb: 15
max_ctb_dsc: "maximum number of beams in cluster at high SNR"
min_snr_t2out: 7.5
min_snr_t2out_dsc: "min SNR in T2 out"
use_gal_dm: 1
use_gal_dm_dsc: "boolean for use of gal dm"
