# configuration for correlator and beamformer
buffers:
  - k: dada
    b: 207618048
    n: 8
    c: 1    
routines:
  - name: dada_dbnull
    cmd: dada_dbnull
    args: -k dada
  - name: dsaX_capture
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_capture
    args: -c 1 -i 127.0.0.1 -o dada -f /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/correlator_header_dsaX.txt
    hostargs:
      corr01: -j 10.41.0.114
      corr02: -j 10.41.0.87
      corr03: -j 10.41.0.91
      corr04: -j 10.41.0.117
      corr05: -j 10.41.0.79
      corr06: -j 10.41.0.58
      corr07: -j 10.41.0.116
      corr08: -j 10.41.0.99
      corr09: -j 10.41.0.66
      corr10: -j 10.41.0.122
      corr11: -j 10.41.0.121
      corr12: -j 10.41.0.61
      corr13: -j 10.41.0.60
      corr14: -j 10.41.0.115
      corr15: -j 10.41.0.113
      corr16: -j 10.41.0.83
