# configuration for correlator with original file writing
buffers:
  - k: dada
    b: 1073741824
    n: 4
    c: 0
  - k: eada
    b: 1073741824
    n: 8
    c: 0
  - k: fada
    b: 1073741824
    n: 4
    c: 0
  - k: bada
    b: 1073741824
    n: 4
    c: 0
  - k: cada
    b: 1073741824
    n: 4
    c: 0
  - k: aada
    b: 1073741824
    n: 4
    c: 0
routines:
  - name: dsaX_writeFil
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_writeFil
    args: -k cada -i 127.0.0.1 -m
    hostargs:
      corr01: -f /home/ubuntu/data/corr01
      corr02: -f /home/ubuntu/data/corr02
      corr09: -f /home/ubuntu/data/corr09
      corr13: -f /home/ubuntu/data/corr13
  - name: heimdall
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-mbheimdall/bin/heimdall
    args: -k bada -gpu_id 0 -nsamps_gulp 16384 -output_dir /home/ubuntu/data -dm 75 1500 -dm_tol 1.5 -max_giant_rate 20000000 -nbeams 64
    hostargs:
      corr01: -coincidencer 10.41.0.46:12345 -beam 0
      corr02: -coincidencer 10.41.0.46:12346 -beam 64
      corr09: -coincidencer 10.41.0.46:12347 -beam 128
      corr13: -coincidencer 10.41.0.46:12348 -beam 192
  - name: dsaX_filTrigger
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_filTrigger
    args: -c 27 -i 127.0.0.1 -n /home/ubuntu/data/fil -j eada -d 
    hostargs:
      corr01: -b 0
      corr02: -b 64
      corr09: -b 128
      corr13: -b 192
  - name: dsaX_simplesplit
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_simplesplit
    args: -c 29 -i aada -o eada -j cada -b
  - name: dsaX_simplesplit
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_simplesplit
    args: -c 28 -i fada -o aada -j bada -b
  - name: gpu_flagger
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/gpu_flagger
    args: -i dada -o fada -t 4.8 -n 7 -p -k 127.0.0.1 -s 10.0
    hostargs:
      corr01: -g /home/ubuntu/data/beams_corr01
      corr02: -g /home/ubuntu/data/beams_corr02
      corr09: -g /home/ubuntu/data/beams_corr09
      corr13: -g /home/ubuntu/data/beams_corr13
  - name: dsaX_nicdb
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_nicdb
    args: -f /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/spectrometer_header.txt -o dada 
    hostargs:
      corr01: -i 10.41.0.114
      corr02: -i 10.41.0.87
      corr09: -i 10.41.0.66
      corr13: -i 10.41.0.60
      
