min_dm: 100.0
min_dm_dsc: "smallest dm in filtering"
max_ibox: 33
max_ibox_dsc: "largest ibox in filtering"
min_snr: 9.0
min_snr_dsc: "smallest snr in filtering"
max_ncl: 30
max_ncl_dsc: "largest number of clusters allowed in triggering"
max_ctb0: 7
max_ctb0_dsc: "maximum number of beams in cluster at min_snr"
max_ctb: 15
max_ctb_dsc: "maximum number of beams in cluster at high SNR"
min_snr_t2out: 9.0
min_snr_t2out_dsc: "min SNR in T2 out"
